
[project]
name = "optibatch"
version = "0.1.0"
description = "Automate MT5 strategy optimization runs"
authors = [{ name="John Davis", email="512jay@gmail.com" }]
dependencies = []

[tool.black]
line-length = 88
